import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Real Estate",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex justify-center`}>
        <div className="w-full w-max-7xl mt-4">
          <NavBar className=""></NavBar>
          {children}
        </div>
      </body>
    </html>
  );
}
